### ISSUE TITLE
Nav Buttons Hover Clickable State Doesn't line up with border on li of ol

### ISSUE THREAD

**Issue by SarahDowling** [SarahDowling/assignment-5#1]
Navigation buttons were only cause the clickable link for a small area of the button, I added padding which extended the clickable area (I could see it in Inspector in Chrome) but I can't figure out how to make the areas even, and the middle box seems to want to extend into the right box's area, so I know I'm not doing it correctly.

HTML for the nav

```
    <header>
            <img class="logo-left" src="img/grain-left.svg" alt="Logo for grains">
            <h1>Grains</h1>
            <img class="logo-left" src="img/grain-right.svg" alt="Logo for grains">

        <nav>
            <ol>
                <li class:"clear"><a href="#intro">Intro</a></li>
                <li class="cereal-line"><a href="#cereals">Cereals</a></li>
                <li><a href="#legumes">Legumes</a></li>
            </ol>
        </nav>
    </header>
```

CSS I think pertains to it

```
nav a{
    padding-bottom:0.5rem;
    padding-top:0.5rem;
    padding-left: 16.6665%;
    padding-right: 16.6665%;
}

nav li:hover {
  background-color: #a93f35;
}

ol{
    text-align: center;
    padding: 0;
}

ol,
a{
    list-style-type: none;
    text-decoration: none;
    color: white;
}
```

Link to webpage: http://sarahdowling.github.io/assignment-5/

@thomasjbradley

**Comment by thomasjbradley** [comment]
Remove the padding and the hover from the `li` itself.
Then, on the `a` tag we need to add a `display` property that will force the `a` tag to take up the whole line of the element its inside.
